"""empty message

Revision ID: 324099abf743
Revises: 5ad510fe6bfc
Create Date: 2024-02-18 15:52:44.664067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '324099abf743'
down_revision = '5ad510fe6bfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('birds', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('birds', 'image')
    # ### end Alembic commands ###
